import type { AuthLocalization } from 'better-auth-ui-svelte';
import * as m from '$lib/paraglide/messages';
import type { UserState } from '$lib/features/users/types.js';
import type { SiteConfig } from '$lib/config/site.server';

/**
 * Converts paraglide messages to better-auth-ui-svelte AuthLocalization format
 * This allows us to use our centralized i18n messages for auth UI components
 */
function getBaseAuthLocalization(): Partial<AuthLocalization> {
	return {
		// Error messages
		INVALID_USERNAME_OR_PASSWORD: m['auth.errors.invalid_username_or_password'](),
		EMAIL_NOT_VERIFIED: m['auth.errors.email_not_verified'](),
		UNEXPECTED_ERROR: m['auth.errors.unexpected_error'](),
		USERNAME_IS_ALREADY_TAKEN: m['auth.errors.username_is_already_taken'](),
		USERNAME_TOO_SHORT: m['auth.errors.username_too_short'](),
		USERNAME_TOO_LONG: m['auth.errors.username_too_long'](),
		INVALID_USERNAME: m['auth.errors.invalid_username'](),
		OTP_NOT_ENABLED: m['auth.errors.otp_not_enabled'](),
		OTP_HAS_EXPIRED: m['auth.errors.otp_has_expired'](),
		TOTP_NOT_ENABLED: m['auth.errors.totp_not_enabled'](),
		TWO_FACTOR_NOT_ENABLED: m['auth.errors.two_factor_not_enabled'](),
		BACKUP_CODES_NOT_ENABLED: m['auth.errors.backup_codes_not_enabled'](),
		INVALID_BACKUP_CODE: m['auth.errors.invalid_backup_code'](),
		INVALID_CODE: m['auth.errors.invalid_code'](),
		TOO_MANY_ATTEMPTS_REQUEST_NEW_CODE: m['auth.errors.too_many_attempts_request_new_code'](),
		INVALID_TWO_FACTOR_COOKIE: m['auth.errors.invalid_two_factor_cookie'](),
		SUBSCRIPTION_NOT_FOUND: m['auth.errors.subscription_not_found'](),
		SUBSCRIPTION_PLAN_NOT_FOUND: m['auth.errors.subscription_plan_not_found'](),
		ALREADY_SUBSCRIBED_PLAN: m['auth.errors.already_subscribed_plan'](),
		UNABLE_TO_CREATE_CUSTOMER: m['auth.errors.unable_to_create_customer'](),
		FAILED_TO_FETCH_PLANS: m['auth.errors.failed_to_fetch_plans'](),
		EMAIL_VERIFICATION_REQUIRED: m['auth.errors.email_verification_required'](),
		SUBSCRIPTION_NOT_ACTIVE: m['auth.errors.subscription_not_active'](),
		SUBSCRIPTION_NOT_SCHEDULED_FOR_CANCELLATION:
			m['auth.errors.subscription_not_scheduled_for_cancellation'](),
		INVALID_PHONE_NUMBER: m['auth.errors.invalid_phone_number'](),
		PHONE_NUMBER_EXIST: m['auth.errors.phone_number_exist'](),
		INVALID_PHONE_NUMBER_OR_PASSWORD: m['auth.errors.invalid_phone_number_or_password'](),
		OTP_NOT_FOUND: m['auth.errors.otp_not_found'](),
		OTP_EXPIRED: m['auth.errors.otp_expired'](),
		INVALID_OTP: m['auth.errors.invalid_otp'](),
		PHONE_NUMBER_NOT_VERIFIED: m['auth.errors.phone_number_not_verified'](),
		CHALLENGE_NOT_FOUND: m['auth.errors.challenge_not_found'](),
		YOU_ARE_NOT_ALLOWED_TO_REGISTER_THIS_PASSKEY:
			m['auth.errors.you_are_not_allowed_to_register_this_passkey'](),
		FAILED_TO_VERIFY_REGISTRATION: m['auth.errors.failed_to_verify_registration'](),
		PASSKEY_NOT_FOUND: m['auth.errors.passkey_not_found'](),
		AUTHENTICATION_FAILED: m['auth.errors.authentication_failed'](),
		UNABLE_TO_CREATE_SESSION: m['auth.errors.unable_to_create_session'](),
		FAILED_TO_UPDATE_PASSKEY: m['auth.errors.failed_to_update_passkey'](),
		YOU_ARE_NOT_ALLOWED_TO_CREATE_A_NEW_ORGANIZATION:
			m['auth.errors.you_are_not_allowed_to_create_a_new_organization'](),
		YOU_HAVE_REACHED_THE_MAXIMUM_NUMBER_OF_ORGANIZATIONS:
			m['auth.errors.you_have_reached_the_maximum_number_of_organizations'](),
		ORGANIZATION_ALREADY_EXISTS: m['auth.errors.organization_already_exists'](),
		ORGANIZATION_NOT_FOUND: m['auth.errors.organization_not_found'](),
		USER_IS_NOT_A_MEMBER_OF_THE_ORGANIZATION:
			m['auth.errors.user_is_not_a_member_of_the_organization'](),
		YOU_ARE_NOT_ALLOWED_TO_UPDATE_THIS_ORGANIZATION:
			m['auth.errors.you_are_not_allowed_to_update_this_organization'](),
		YOU_ARE_NOT_ALLOWED_TO_DELETE_THIS_ORGANIZATION:
			m['auth.errors.you_are_not_allowed_to_delete_this_organization'](),
		NO_ACTIVE_ORGANIZATION: m['auth.errors.no_active_organization'](),
		USER_IS_ALREADY_A_MEMBER_OF_THIS_ORGANIZATION:
			m['auth.errors.user_is_already_a_member_of_this_organization'](),
		MEMBER_NOT_FOUND: m['auth.errors.member_not_found'](),
		ROLE_NOT_FOUND: m['auth.errors.role_not_found'](),
		YOU_ARE_NOT_ALLOWED_TO_CREATE_A_NEW_TEAM:
			m['auth.errors.you_are_not_allowed_to_create_a_new_team'](),
		TEAM_ALREADY_EXISTS: m['auth.errors.team_already_exists'](),
		TEAM_NOT_FOUND: m['auth.errors.team_not_found'](),
		YOU_CANNOT_LEAVE_THE_ORGANIZATION_AS_THE_ONLY_OWNER:
			m['auth.errors.you_cannot_leave_the_organization_as_the_only_owner'](),
		YOU_ARE_NOT_ALLOWED_TO_DELETE_THIS_MEMBER:
			m['auth.errors.you_are_not_allowed_to_delete_this_member'](),
		YOU_ARE_NOT_ALLOWED_TO_INVITE_USERS_TO_THIS_ORGANIZATION:
			m['auth.errors.you_are_not_allowed_to_invite_users_to_this_organization'](),
		USER_IS_ALREADY_INVITED_TO_THIS_ORGANIZATION:
			m['auth.errors.user_is_already_invited_to_this_organization'](),
		INVITATION_NOT_FOUND: m['auth.errors.invitation_not_found'](),
		YOU_ARE_NOT_THE_RECIPIENT_OF_THE_INVITATION:
			m['auth.errors.you_are_not_the_recipient_of_the_invitation'](),
		YOU_ARE_NOT_ALLOWED_TO_CANCEL_THIS_INVITATION:
			m['auth.errors.you_are_not_allowed_to_cancel_this_invitation'](),
		INVITER_IS_NO_LONGER_A_MEMBER_OF_THE_ORGANIZATION:
			m['auth.errors.inviter_is_no_longer_a_member_of_the_organization'](),
		YOU_ARE_NOT_ALLOWED_TO_INVITE_USER_WITH_THIS_ROLE:
			m['auth.errors.you_are_not_allowed_to_invite_user_with_this_role'](),
		FAILED_TO_RETRIEVE_INVITATION: m['auth.errors.failed_to_retrieve_invitation'](),
		YOU_HAVE_REACHED_THE_MAXIMUM_NUMBER_OF_TEAMS:
			m['auth.errors.you_have_reached_the_maximum_number_of_teams'](),
		UNABLE_TO_REMOVE_LAST_TEAM: m['auth.errors.unable_to_remove_last_team'](),
		YOU_ARE_NOT_ALLOWED_TO_UPDATE_THIS_MEMBER:
			m['auth.errors.you_are_not_allowed_to_update_this_member'](),
		ORGANIZATION_MEMBERSHIP_LIMIT_REACHED: m['auth.errors.organization_membership_limit_reached'](),
		YOU_ARE_NOT_ALLOWED_TO_CREATE_TEAMS_IN_THIS_ORGANIZATION:
			m['auth.errors.you_are_not_allowed_to_create_teams_in_this_organization'](),
		YOU_ARE_NOT_ALLOWED_TO_DELETE_TEAMS_IN_THIS_ORGANIZATION:
			m['auth.errors.you_are_not_allowed_to_delete_teams_in_this_organization'](),
		YOU_ARE_NOT_ALLOWED_TO_UPDATE_THIS_TEAM:
			m['auth.errors.you_are_not_allowed_to_update_this_team'](),
		YOU_ARE_NOT_ALLOWED_TO_DELETE_THIS_TEAM:
			m['auth.errors.you_are_not_allowed_to_delete_this_team'](),
		INVITATION_LIMIT_REACHED: m['auth.errors.invitation_limit_reached'](),
		INVALID_SESSION_TOKEN: m['auth.errors.invalid_session_token'](),
		PASSWORD_COMPROMISED: m['auth.errors.password_compromised'](),
		INVALID_OAUTH_CONFIGURATION: m['auth.errors.invalid_oauth_configuration'](),
		INVALID_EMAIL: m['auth.errors.invalid_email'](),
		USER_NOT_FOUND: m['auth.errors.user_not_found'](),
		TOO_MANY_ATTEMPTS: m['auth.errors.too_many_attempts'](),
		MISSING_SECRET_KEY: m['auth.errors.missing_secret_key'](),
		SERVICE_UNAVAILABLE: m['auth.errors.service_unavailable'](),
		VERIFICATION_FAILED: m['auth.errors.verification_failed'](),
		MISSING_RESPONSE: m['auth.errors.missing_response'](),
		UNKNOWN_ERROR: m['auth.errors.unknown_error'](),
		INVALID_METADATA_TYPE: m['auth.errors.invalid_metadata_type'](),
		REFILL_AMOUNT_AND_INTERVAL_REQUIRED: m['auth.errors.refill_amount_and_interval_required'](),
		REFILL_INTERVAL_AND_AMOUNT_REQUIRED: m['auth.errors.refill_interval_and_amount_required'](),
		USER_BANNED: m['auth.errors.user_banned'](),
		UNAUTHORIZED_SESSION: m['auth.errors.unauthorized_session'](),
		KEY_NOT_FOUND: m['auth.errors.key_not_found'](),
		KEY_DISABLED: m['auth.errors.key_disabled'](),
		KEY_EXPIRED: m['auth.errors.key_expired'](),
		USAGE_EXCEEDED: m['auth.errors.usage_exceeded'](),
		KEY_NOT_RECOVERABLE: m['auth.errors.key_not_recoverable'](),
		EXPIRES_IN_IS_TOO_SMALL: m['auth.errors.expires_in_is_too_small'](),
		EXPIRES_IN_IS_TOO_LARGE: m['auth.errors.expires_in_is_too_large'](),
		INVALID_REMAINING: m['auth.errors.invalid_remaining'](),
		INVALID_PREFIX_LENGTH: m['auth.errors.invalid_prefix_length'](),
		INVALID_NAME_LENGTH: m['auth.errors.invalid_name_length'](),
		METADATA_DISABLED: m['auth.errors.metadata_disabled'](),
		RATE_LIMIT_EXCEEDED: m['auth.errors.rate_limit_exceeded'](),
		NO_VALUES_TO_UPDATE: m['auth.errors.no_values_to_update'](),
		KEY_DISABLED_EXPIRATION: m['auth.errors.key_disabled_expiration'](),
		INVALID_API_KEY: m['auth.errors.invalid_api_key'](),
		INVALID_USER_ID_FROM_API_KEY: m['auth.errors.invalid_user_id_from_api_key'](),
		INVALID_API_KEY_GETTER_RETURN_TYPE: m['auth.errors.invalid_api_key_getter_return_type'](),
		SERVER_ONLY_PROPERTY: m['auth.errors.server_only_property'](),
		FAILED_TO_CREATE_USER: m['auth.errors.failed_to_create_user'](),
		COULD_NOT_CREATE_SESSION: m['auth.errors.could_not_create_session'](),
		ANONYMOUS_USERS_CANNOT_SIGN_IN_AGAIN_ANONYMOUSLY:
			m['auth.errors.anonymous_users_cannot_sign_in_again_anonymously'](),
		USER_ALREADY_EXISTS: m['auth.errors.user_already_exists'](),
		YOU_CANNOT_BAN_YOURSELF: m['auth.errors.you_cannot_ban_yourself'](),
		YOU_ARE_NOT_ALLOWED_TO_CHANGE_USERS_ROLE:
			m['auth.errors.you_are_not_allowed_to_change_users_role'](),
		YOU_ARE_NOT_ALLOWED_TO_CREATE_USERS: m['auth.errors.you_are_not_allowed_to_create_users'](),
		YOU_ARE_NOT_ALLOWED_TO_LIST_USERS: m['auth.errors.you_are_not_allowed_to_list_users'](),
		YOU_ARE_NOT_ALLOWED_TO_LIST_USERS_SESSIONS:
			m['auth.errors.you_are_not_allowed_to_list_users_sessions'](),
		YOU_ARE_NOT_ALLOWED_TO_BAN_USERS: m['auth.errors.you_are_not_allowed_to_ban_users'](),
		YOU_ARE_NOT_ALLOWED_TO_IMPERSONATE_USERS:
			m['auth.errors.you_are_not_allowed_to_impersonate_users'](),
		YOU_ARE_NOT_ALLOWED_TO_REVOKE_USERS_SESSIONS:
			m['auth.errors.you_are_not_allowed_to_revoke_users_sessions'](),
		YOU_ARE_NOT_ALLOWED_TO_DELETE_USERS: m['auth.errors.you_are_not_allowed_to_delete_users'](),
		YOU_ARE_NOT_ALLOWED_TO_SET_USERS_PASSWORD:
			m['auth.errors.you_are_not_allowed_to_set_users_password'](),
		BANNED_USER: m['auth.errors.banned_user'](),
		FAILED_TO_CREATE_SESSION: m['auth.errors.failed_to_create_session'](),
		FAILED_TO_UPDATE_USER: m['auth.errors.failed_to_update_user'](),
		FAILED_TO_GET_SESSION: m['auth.errors.failed_to_get_session'](),
		INVALID_PASSWORD: m['auth.errors.invalid_password'](),
		INVALID_EMAIL_OR_PASSWORD: m['auth.errors.invalid_email_or_password'](),
		SOCIAL_ACCOUNT_ALREADY_LINKED: m['auth.errors.social_account_already_linked'](),
		PROVIDER_NOT_FOUND: m['auth.errors.provider_not_found'](),
		INVALID_TOKEN: m['auth.errors.invalid_token'](),
		ID_TOKEN_NOT_SUPPORTED: m['auth.errors.id_token_not_supported'](),
		FAILED_TO_GET_USER_INFO: m['auth.errors.failed_to_get_user_info'](),
		USER_EMAIL_NOT_FOUND: m['auth.errors.user_email_not_found'](),
		PASSWORD_TOO_SHORT: m['auth.errors.password_too_short'](),
		PASSWORD_TOO_LONG: m['auth.errors.password_too_long'](),
		EMAIL_CAN_NOT_BE_UPDATED: m['auth.errors.email_can_not_be_updated'](),
		CREDENTIAL_ACCOUNT_NOT_FOUND: m['auth.errors.credential_account_not_found'](),
		SESSION_EXPIRED: m['auth.errors.session_expired'](),
		FAILED_TO_UNLINK_LAST_ACCOUNT: m['auth.errors.failed_to_unlink_last_account'](),
		ACCOUNT_NOT_FOUND: m['auth.errors.account_not_found'](),
		USER_ALREADY_HAS_PASSWORD: m['auth.errors.user_already_has_password'](),

		// UI Labels
		APP: m['auth.app'](),
		ACCOUNT: m['auth.account'](),
		ACCOUNTS: m['auth.accounts'](),
		ACCOUNTS_DESCRIPTION: m['auth.accounts_description'](),
		ACCOUNTS_INSTRUCTIONS: m['auth.accounts_instructions'](),
		ADD_ACCOUNT: m['auth.add_account'](),
		ADD_PASSKEY: m['auth.add_passkey'](),
		ALREADY_HAVE_AN_ACCOUNT: m['auth.already_have_an_account'](),
		AVATAR: m['auth.avatar'](),
		AVATAR_DESCRIPTION: m['auth.avatar_description'](),
		AVATAR_INSTRUCTIONS: m['auth.avatar_instructions'](),
		BACKUP_CODE_REQUIRED: m['auth.backup_code_required'](),
		BACKUP_CODES: m['auth.backup_codes'](),
		BACKUP_CODES_DESCRIPTION: m['auth.backup_codes_description'](),
		BACKUP_CODE_PLACEHOLDER: m['auth.backup_code_placeholder'](),
		BACKUP_CODE: m['auth.backup_code'](),
		CANCEL: m['auth.cancel'](),
		CHANGE_PASSWORD: m['auth.change_password'](),
		CHANGE_PASSWORD_DESCRIPTION: m['auth.change_password_description'](),
		CHANGE_PASSWORD_INSTRUCTIONS: m['auth.change_password_instructions'](),
		CHANGE_PASSWORD_SUCCESS: m['auth.change_password_success'](),
		CONFIRM_PASSWORD: m['auth.confirm_password'](),
		CONFIRM_PASSWORD_PLACEHOLDER: m['auth.confirm_password_placeholder'](),
		CONFIRM_PASSWORD_REQUIRED: m['auth.confirm_password_required'](),
		CONTINUE_WITH_AUTHENTICATOR: m['auth.continue_with_authenticator'](),
		COPIED_TO_CLIPBOARD: m['auth.copied_to_clipboard'](),
		COPY_TO_CLIPBOARD: m['auth.copy_to_clipboard'](),
		COPY_ALL_CODES: m['auth.copy_all_codes'](),
		CONTINUE: m['auth.continue'](),
		CURRENT_PASSWORD: m['auth.current_password'](),
		CURRENT_PASSWORD_PLACEHOLDER: m['auth.current_password_placeholder'](),
		CURRENT_SESSION: m['auth.current_session'](),
		DELETE: m['auth.delete'](),
		DELETE_AVATAR: m['auth.delete_avatar'](),
		DELETE_ACCOUNT: m['auth.delete_account'](),
		DELETE_ACCOUNT_DESCRIPTION: m['auth.delete_account_description'](),
		DELETE_ACCOUNT_INSTRUCTIONS: m['auth.delete_account_instructions'](),
		DELETE_ACCOUNT_VERIFY: m['auth.delete_account_verify'](),
		DELETE_ACCOUNT_SUCCESS: m['auth.delete_account_success'](),
		DISABLE_TWO_FACTOR: m['auth.disable_two_factor'](),
		DISABLED_CREDENTIALS_DESCRIPTION: m['auth.disabled_credentials_description'](),
		DONT_HAVE_AN_ACCOUNT: m['auth.dont_have_an_account'](),
		DONE: m['auth.done'](),
		EMAIL: m['auth.email'](),
		EMAIL_DESCRIPTION: m['auth.email_description'](),
		EMAIL_INSTRUCTIONS: m['auth.email_instructions'](),
		EMAIL_IS_THE_SAME: m['auth.email_is_the_same'](),
		EMAIL_PLACEHOLDER: m['auth.email_placeholder'](),
		EMAIL_REQUIRED: m['auth.email_required'](),
		EMAIL_VERIFY_CHANGE: m['auth.email_verify_change'](),
		EMAIL_VERIFICATION: m['auth.email_verification'](),
		ENABLE_TWO_FACTOR: m['auth.enable_two_factor'](),
		IS_INVALID: m['auth.is_invalid'](),
		IS_REQUIRED: m['auth.is_required'](),
		IS_THE_SAME: m['auth.is_the_same'](),
		FORGOT_AUTHENTICATOR: m['auth.forgot_authenticator'](),
		FORGOT_PASSWORD: m['auth.forgot_password'](),
		FORGOT_PASSWORD_ACTION: m['auth.forgot_password_action'](),
		FORGOT_PASSWORD_DESCRIPTION: m['auth.forgot_password_description'](),
		FORGOT_PASSWORD_EMAIL: m['auth.forgot_password_email'](),
		FORGOT_PASSWORD_LINK: m['auth.forgot_password_link'](),
		LINK: m['auth.link'](),
		MAGIC_LINK: m['auth.magic_link'](),
		MAGIC_LINK_ACTION: m['auth.magic_link_action'](),
		MAGIC_LINK_DESCRIPTION: m['auth.magic_link_description'](),
		MAGIC_LINK_EMAIL: m['auth.magic_link_email'](),
		EMAIL_OTP: m['auth.email_otp'](),
		EMAIL_OTP_SEND_ACTION: m['auth.email_otp_send_action'](),
		EMAIL_OTP_VERIFY_ACTION: m['auth.email_otp_verify_action'](),
		EMAIL_OTP_DESCRIPTION: m['auth.email_otp_description'](),
		EMAIL_OTP_VERIFICATION_SENT: m['auth.email_otp_verification_sent'](),
		NAME: m['auth.name'](),
		NAME_DESCRIPTION: m['auth.name_description'](),
		NAME_INSTRUCTIONS: m['auth.name_instructions'](),
		NAME_PLACEHOLDER: m['auth.name_placeholder'](),
		NEW_PASSWORD: m['auth.new_password'](),
		NEW_PASSWORD_PLACEHOLDER: m['auth.new_password_placeholder'](),
		NEW_PASSWORD_REQUIRED: m['auth.new_password_required'](),
		ONE_TIME_PASSWORD: m['auth.one_time_password'](),
		OR_CONTINUE_WITH: m['auth.or_continue_with'](),
		PASSKEY: m['auth.passkey'](),
		PASSKEYS: m['auth.passkeys'](),
		PASSKEYS_DESCRIPTION: m['auth.passkeys_description'](),
		PASSKEYS_INSTRUCTIONS: m['auth.passkeys_instructions'](),
		PERSONAL_ACCOUNT: m['auth.personal_account'](),
		API_KEYS: m['auth.api_keys'](),
		API_KEYS_DESCRIPTION: m['auth.api_keys_description'](),
		API_KEYS_INSTRUCTIONS: m['auth.api_keys_instructions'](),
		CREATE_API_KEY: m['auth.create_api_key'](),
		CREATE_API_KEY_DESCRIPTION: m['auth.create_api_key_description'](),
		API_KEY_NAME_PLACEHOLDER: m['auth.api_key_name_placeholder'](),
		API_KEY_CREATED: m['auth.api_key_created'](),
		CREATE_API_KEY_SUCCESS: m['auth.create_api_key_success'](),
		NEVER_EXPIRES: m['auth.never_expires'](),
		EXPIRES: m['auth.expires'](),
		NO_EXPIRATION: m['auth.no_expiration'](),
		CREATE_ORGANIZATION: m['auth.create_organization'](),
		ORGANIZATION: m['auth.organization'](),
		ORGANIZATION_NAME: m['auth.organization_name'](),
		ORGANIZATION_NAME_PLACEHOLDER: m['auth.organization_name_placeholder'](),
		ORGANIZATION_NAME_DESCRIPTION: m['auth.organization_name_description'](),
		ORGANIZATION_NAME_INSTRUCTIONS: m['auth.organization_name_instructions'](),
		ORGANIZATION_SLUG: m['auth.organization_slug'](),
		ORGANIZATION_SLUG_DESCRIPTION: m['auth.organization_slug_description'](),
		ORGANIZATION_SLUG_INSTRUCTIONS: m['auth.organization_slug_instructions'](),
		ORGANIZATION_SLUG_PLACEHOLDER: m['auth.organization_slug_placeholder'](),
		CREATE_ORGANIZATION_SUCCESS: m['auth.create_organization_success'](),
		PASSWORD: m['auth.password'](),
		PASSWORD_PLACEHOLDER: m['auth.password_placeholder'](),
		PASSWORD_REQUIRED: m['auth.password_required'](),
		PASSWORDS_DO_NOT_MATCH: m['auth.passwords_do_not_match'](),
		PROVIDERS: m['auth.providers'](),
		PROVIDERS_DESCRIPTION: m['auth.providers_description'](),
		RECOVER_ACCOUNT: m['auth.recover_account'](),
		RECOVER_ACCOUNT_ACTION: m['auth.recover_account_action'](),
		RECOVER_ACCOUNT_DESCRIPTION: m['auth.recover_account_description'](),
		REMEMBER_ME: m['auth.remember_me'](),
		RESEND_CODE: m['auth.resend_code'](),
		RESEND_VERIFICATION_EMAIL: m['auth.resend_verification_email'](),
		RESET_PASSWORD: m['auth.reset_password'](),
		RESET_PASSWORD_ACTION: m['auth.reset_password_action'](),
		RESET_PASSWORD_DESCRIPTION: m['auth.reset_password_description'](),
		RESET_PASSWORD_SUCCESS: m['auth.reset_password_success'](),
		REQUEST_FAILED: m['auth.request_failed'](),
		REVOKE: m['auth.revoke'](),
		DELETE_API_KEY: m['auth.delete_api_key'](),
		DELETE_API_KEY_CONFIRM: m['auth.delete_api_key_confirm'](),
		API_KEY: m['auth.api_key'](),
		SIGN_IN: m['auth.sign_in'](),
		SIGN_IN_ACTION: m['auth.sign_in_action'](),
		SIGN_IN_DESCRIPTION: m['auth.sign_in_description'](),
		SIGN_IN_USERNAME_DESCRIPTION: m['auth.sign_in_username_description'](),
		SIGN_IN_WITH: m['auth.sign_in_with'](),
		SIGN_OUT: m['auth.sign_out'](),
		SIGN_UP: m['auth.sign_up'](),
		SIGN_UP_ACTION: m['auth.sign_up_action'](),
		SIGN_UP_DESCRIPTION: m['auth.sign_up_description'](),
		SIGN_UP_EMAIL: m['auth.sign_up_email'](),
		SESSIONS: m['auth.sessions'](),
		SESSIONS_DESCRIPTION: m['auth.sessions_description'](),
		SET_PASSWORD: m['auth.set_password'](),
		SET_PASSWORD_DESCRIPTION: m['auth.set_password_description'](),
		SETTINGS: m['auth.settings'](),
		SAVE: m['auth.save'](),
		SECURITY: m['auth.security'](),
		SWITCH_ACCOUNT: m['auth.switch_account'](),
		TRUST_DEVICE: m['auth.trust_device'](),
		TWO_FACTOR: m['auth.two_factor'](),
		TWO_FACTOR_ACTION: m['auth.two_factor_action'](),
		TWO_FACTOR_DESCRIPTION: m['auth.two_factor_description'](),
		TWO_FACTOR_CARD_DESCRIPTION: m['auth.two_factor_card_description'](),
		TWO_FACTOR_DISABLE_INSTRUCTIONS: m['auth.two_factor_disable_instructions'](),
		TWO_FACTOR_ENABLE_INSTRUCTIONS: m['auth.two_factor_enable_instructions'](),
		TWO_FACTOR_ENABLED: m['auth.two_factor_enabled'](),
		TWO_FACTOR_DISABLED: m['auth.two_factor_disabled'](),
		TWO_FACTOR_PROMPT: m['auth.two_factor_prompt'](),
		TWO_FACTOR_TOTP_LABEL: m['auth.two_factor_totp_label'](),
		SEND_VERIFICATION_CODE: m['auth.send_verification_code'](),
		UNLINK: m['auth.unlink'](),
		UPDATED_SUCCESSFULLY: m['auth.updated_successfully'](),
		USERNAME: m['auth.username'](),
		USERNAME_DESCRIPTION: m['auth.username_description'](),
		USERNAME_INSTRUCTIONS: m['auth.username_instructions'](),
		USERNAME_PLACEHOLDER: m['auth.username_placeholder'](),
		SIGN_IN_USERNAME_PLACEHOLDER: m['auth.sign_in_username_placeholder'](),
		VERIFY_YOUR_EMAIL: m['auth.verify_your_email'](),
		VERIFY_YOUR_EMAIL_DESCRIPTION: m['auth.verify_your_email_description'](),
		GO_BACK: m['auth.go_back'](),
		SESSION_NOT_FRESH: m['auth.session_not_fresh'](),
		UPLOAD_AVATAR: m['auth.upload_avatar'](),
		LOGO: m['auth.logo'](),
		LOGO_DESCRIPTION: m['auth.logo_description'](),
		LOGO_INSTRUCTIONS: m['auth.logo_instructions'](),
		UPLOAD: m['auth.upload'](),
		UPLOAD_LOGO: m['auth.upload_logo'](),
		DELETE_LOGO: m['auth.delete_logo'](),
		PRIVACY_POLICY: m['auth.privacy_policy'](),
		TERMS_OF_SERVICE: m['auth.terms_of_service'](),
		PROTECTED_BY_RECAPTCHA: m['auth.protected_by_recaptcha'](),
		BY_CONTINUING_YOU_AGREE: m['auth.by_continuing_you_agree'](),
		USER: m['auth.user'](),
		ORGANIZATIONS: m['auth.organizations'](),
		ORGANIZATIONS_DESCRIPTION: m['auth.organizations_description'](),
		ORGANIZATIONS_INSTRUCTIONS: m['auth.organizations_instructions'](),
		LEAVE_ORGANIZATION: m['auth.leave_organization'](),
		LEAVE_ORGANIZATION_CONFIRM: m['auth.leave_organization_confirm'](),
		LEAVE_ORGANIZATION_SUCCESS: m['auth.leave_organization_success'](),
		MANAGE_ORGANIZATION: m['auth.manage_organization'](),
		REMOVE_MEMBER: m['auth.remove_member'](),
		REMOVE_MEMBER_CONFIRM: m['auth.remove_member_confirm'](),
		REMOVE_MEMBER_SUCCESS: m['auth.remove_member_success'](),
		INVITE_MEMBER: m['auth.invite_member'](),
		MEMBERS: m['auth.members'](),
		MEMBERS_DESCRIPTION: m['auth.members_description'](),
		MEMBERS_INSTRUCTIONS: m['auth.members_instructions'](),
		INVITE_MEMBER_DESCRIPTION: m['auth.invite_member_description'](),
		ROLE: m['auth.role'](),
		SELECT_ROLE: m['auth.select_role'](),
		ADMIN: m['auth.admin'](),
		MEMBER: m['auth.member'](),
		GUEST: m['auth.guest'](),
		OWNER: m['auth.owner'](),
		UPDATE_ROLE_DESCRIPTION: m['auth.update_role_description'](),
		UPDATE_ROLE: m['auth.update_role'](),
		MEMBER_ROLE_UPDATED: m['auth.member_role_updated'](),
		SEND_INVITATION: m['auth.send_invitation'](),
		SEND_INVITATION_SUCCESS: m['auth.send_invitation_success'](),
		PENDING_INVITATIONS: m['auth.pending_invitations'](),
		PENDING_INVITATIONS_DESCRIPTION: m['auth.pending_invitations_description'](),
		PENDING_USER_INVITATIONS_DESCRIPTION: m['auth.pending_user_invitations_description'](),
		CANCEL_INVITATION: m['auth.cancel_invitation'](),
		INVITATION_CANCELLED: m['auth.invitation_cancelled'](),
		ACCEPT_INVITATION: m['auth.accept_invitation'](),
		ACCEPT_INVITATION_DESCRIPTION: m['auth.accept_invitation_description'](),
		INVITATION_ACCEPTED: m['auth.invitation_accepted'](),
		INVITATION_REJECTED: m['auth.invitation_rejected'](),
		ACCEPT: m['auth.accept'](),
		REJECT: m['auth.reject'](),
		INVITATION_EXPIRED: m['auth.invitation_expired'](),
		DELETE_ORGANIZATION: m['auth.delete_organization'](),
		DELETE_ORGANIZATION_DESCRIPTION: m['auth.delete_organization_description'](),
		DELETE_ORGANIZATION_SUCCESS: m['auth.delete_organization_success'](),
		DELETE_ORGANIZATION_INSTRUCTIONS: m['auth.delete_organization_instructions'](),
		SLUG_REQUIRED: m['auth.slug_required'](),
		SLUG_DOES_NOT_MATCH: m['auth.slug_does_not_match'](),
		UNKNOWN: m['auth.unknown']()
	};
}

/**
 * Get auth localization with user-type-specific overrides
 * @param userType - The type of user (talent or recruiter)
 * @returns Localization object with appropriate SIGN_UP text for the user type
 */
export function getAuthLocalization(
	userType: UserState | null = 'talent',
	config: SiteConfig
): Partial<AuthLocalization> {
	const base = getBaseAuthLocalization();

	// Override SIGN_UP based on user type
	if (userType === 'talent') {
		return {
			...base,
			SIGN_UP: m['auth.sign_up_talent']()
		};
	}

	if (userType === 'recruiter') {
		return {
			...base,
			SIGN_UP: m['auth.sign_up_recruiter']({ appName: config.appName })
		};
	}

	// Default fallback
	return base;
}
